# 加载常用包
library(here)
library(haven)
library(readxl)
library(car)
library(DescTools)
library(rstatix)
library(tidyverse)  
library(bruceR)     
library(psych)
library(lme4)
library(lmerTest)
library(emmeans)
library(effectsize)
library(HH)
library(irr)
library(agricolae)
library(ggplot2)
library(gridExtra)
library(ppcor)
library(aod)
library(lmtest)
library(ResourceSelection)
library(pscl)
library('multcomp')
library('emmeans')
library(lme4)
library('mvnormtest')
library('dplyr')
library('heplots')
library(BSDA)
# 设置全局选项（可选）
options(scipen = 999)  # 避免科学计数法